#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Mar 31, 2020 11:43:11 AM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1100x650+326+171
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra44 \
        -borderwidth 2 -relief groove -background #F3F3F3 -height 705 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 205 
    vTcl:DefineAlias "$top.fra44" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu46 \
        -command open_files -takefocus {} -text {Open Folder} 
    vTcl:DefineAlias "$site_3_0.tBu46" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu47 \
        -command next_image -takefocus {} -text {Next Image} 
    vTcl:DefineAlias "$site_3_0.tBu47" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu48 \
        -command previous_image -takefocus {} -text {Previous Image} 
    vTcl:DefineAlias "$site_3_0.tBu48" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu49 \
        -command save_annotation -takefocus {} -text {Save Annotation} 
    vTcl:DefineAlias "$site_3_0.tBu49" "TButton4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu46 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.092 -width 160 \
        -relwidth 0 -height 60 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu47 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.292 -width 160 \
        -relwidth 0 -height 60 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu48 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.492 -width 160 \
        -relwidth 0 -height 60 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu49 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.692 -width 160 \
        -relwidth 0 -height 60 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra51 \
        -borderwidth 2 -background #F3F3F3 -height 650 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 250 
    vTcl:DefineAlias "$top.fra51" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra51
    label $site_3_0.lab52 \
        -activebackground #595959 -activeforeground black -background #FFFFFF \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 16} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -highlightthickness 2 -relief groove -text {Select Model} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra54 \
        -borderwidth 2 -relief groove -background #FFFFFF -height 185 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 215 
    vTcl:DefineAlias "$site_3_0.fra54" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra54
    checkbutton $site_4_0.che44 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background #FFFFFF -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 11} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {faster_rcnn_inceptio
n_v2_coco
} \
        -variable model1 
    vTcl:DefineAlias "$site_4_0.che44" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #FFFFFF -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {ssd_inception_v2_
coco} -variable model2 
    vTcl:DefineAlias "$site_4_0.che45" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.che45 <<SetBalloon>> {
        set ::vTcl::balloon::%W {ssd_inception_v2_
coco}
    }
    checkbutton $site_4_0.che46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #FFFFFF -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {ssdlite_mobilenet
_v2_coco} -variable model3 
    vTcl:DefineAlias "$site_4_0.che46" "Checkbutton3" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.che44 \
        -in $site_4_0 -x 0 -relx 0.047 -y 0 -rely 0.054 -width 0 \
        -relwidth 0.921 -height 0 -relheight 0.33 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che45 \
        -in $site_4_0 -x 0 -relx 0.047 -y 0 -rely 0.324 -width 0 \
        -relwidth 0.921 -height 0 -relheight 0.292 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che46 \
        -in $site_4_0 -x 0 -relx 0.047 -y 0 -rely 0.649 -width 0 \
        -relwidth 0.921 -height 0 -relheight 0.346 -anchor nw \
        -bordermode ignore 
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #FFFFFF \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 14} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief ridge -text {Detection
Threshold} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable threshold -width 44 
    vTcl:DefineAlias "$site_3_0.ent48" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.ent48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {value beween 0 and 1}
    }
    frame $site_3_0.fra51 \
        -borderwidth 2 -relief groove -background #FFFFFF -height 214 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 215 
    vTcl:DefineAlias "$site_3_0.fra51" "Frame5" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra51
    checkbutton $site_4_0.che56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #FFFFFF -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {  Person} -variable person_check 
    vTcl:DefineAlias "$site_4_0.che56" "Checkbutton4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #FFFFFF -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {  Cat} -variable cat_check 
    vTcl:DefineAlias "$site_4_0.che57" "Checkbutton5" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #FFFFFF -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {  Dog} -variable dog_check 
    vTcl:DefineAlias "$site_4_0.che58" "Checkbutton6" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #FFFFFF -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {  Bottle} -variable bottle_check 
    vTcl:DefineAlias "$site_4_0.che59" "Checkbutton7" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background #FFFFFF -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {  Chair} -variable chair_check 
    vTcl:DefineAlias "$site_4_0.che60" "Checkbutton8" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.che56 \
        -in $site_4_0 -x 0 -relx 0.047 -y 0 -rely 0.043 -width 0 \
        -relwidth 0.874 -height 0 -relheight 0.132 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che57 \
        -in $site_4_0 -x 0 -relx 0.047 -y 0 -rely 0.234 -width 0 \
        -relwidth 0.874 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che58 \
        -in $site_4_0 -x 0 -relx 0.047 -y 0 -rely 0.421 -width 0 \
        -relwidth 0.874 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che59 \
        -in $site_4_0 -x 0 -relx 0.047 -y 0 -rely 0.607 -width 0 \
        -relwidth 0.874 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che60 \
        -in $site_4_0 -x 0 -relx 0.047 -y 0 -rely 0.794 -width 0 \
        -relwidth 0.874 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
    button $site_3_0.but54 \
        -activebackground #f9f9f9 -activeforeground black -background #FFFFFF \
        -command detect_image -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Detect 
    vTcl:DefineAlias "$site_3_0.but54" "Button1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.08 -y 0 -rely 0.015 -width 0 \
        -relwidth 0.848 -height 0 -relheight 0.071 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra54 \
        -in $site_3_0 -x 0 -relx 0.08 -y 0 -rely 0.108 -width 0 \
        -relwidth 0.86 -height 0 -relheight 0.285 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.08 -y 0 -rely 0.415 -width 0 \
        -relwidth 0.608 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.72 -y 0 -rely 0.431 -width 0 \
        -relwidth 0.18 -height 45 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra51 \
        -in $site_3_0 -x 0 -relx 0.08 -y 0 -rely 0.538 -width 0 \
        -relwidth 0.86 -height 0 -relheight 0.329 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.08 -y 0 -rely 0.892 -width 215 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra49 \
        -borderwidth 2 -relief groove -background #FFFFFF -height 650 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 676 
    vTcl:DefineAlias "$top.fra49" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra49
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #FFFFFF \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Image 
    vTcl:DefineAlias "$site_3_0.lab50" "Label3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1.004 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra44 \
        -in $top -x 0 -y 0 -width 0 -relwidth 0.167 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    place $top.fra51 \
        -in $top -x 0 -relx 0.773 -y 0 -width 0 -relwidth 0.227 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 0 -relx 0.164 -y 0 -width 0 -relwidth 0.615 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

